on:
  issues:
    types: [open]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: nc-animation/github-action@master
        env:
          TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          EVENT: ${{ toJson(github.event) }}
